version: "3.9"
services:
  postgres:
    container_name: postgresql_database
    image: postgres
    restart: always
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      
  
  redis:
    container_name: redis_inst
    image: redis
    restart: always
    ports:
      - "6379:6379"
      
  upload_api:
    container_name: upload_api_inst
    build: .
    command: uvicorn main_upload_api:app --host "0.0.0.0" --port ${API_PORT}
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./appdata:/api/appdata
      - ./logs:/api/logs
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 5050:80
    depends_on:
      - postgres

  flower:
    container_name: flower_inst
    build: .
    command: celery -A celery_worker.celery flower --port=5555
    ports:
      - 5556:5555
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      # - api
      - redis
      - celery_worker


 
  celery_worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
      - ./appdata:/api/appdata
      - ./logs:/api/logs

    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - redis
      - postgres