version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
  
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  redis:
    image: redis
    ports:
      - "6379:6379"
      