name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: cp env_example .env && mkdir -p logs && mkdir -p appdata  && docker-compose up -d --remove-orphans --build && docker ps --all
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python test dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          mkdir -p logs && mkdir -p appdata
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
    - name: Test with pytest
      run: |
        sleep 1
        # pytest
        python3 tests/test_simple.py
        echo "+++++++++++ celery_worker_0 +++++++++++ "
        docker logs celery_worker_0
        echo ""+++++++++++ celery_worker_1+++++++++++"
        docker logs celery_worker_1
        echo "+++++++++++ upload_api_inst "+++++++++++
        docker logs upload_api_inst